nome = str(input('Qual seu nome? '))
sobrenome = str(input('Qual seu sobrenome? '))
idade = int(input('Qual sua idade? '))
nascimento = int(input('Ano de nascimento: '))
maior = bool(idade >= 18)
altura = float(input('Altura em metros: '))
print('\n • Nome:', nome)
print(' • Sobrenome:', sobrenome)
print(' • Idade:', idade)
print(' • Ano de nascimento:', nascimento)
print(' • É maior de idade?', maior)
print(' • Altura em metros:', altura)