# Faça um programa que leia algo e diga o tipo primitivo, e todas as informações sobre ela
a = input('Digite algo: ')
print('o tipo primitivo desse valor é:', '{}', type(a), '{}'.format('\033[36m', '\033[m'))
print('este valor é um número/letra?', '{}', a.isalnum(), '{}'.format('\033[36m', '\033[m'))
print('este valor é uma letra?', '{}', a.isalpha(), '{}'.format('\033[36m', '\033[m'))
print('este valor é um código padrão para troca de informações?', '{}', a.isascii(), '{}'.format('\033[36m', '\033[m'))
print('este valor é um digito?', '{}', a.isdigit(), '{}'.format('\033[36m', '\033[m'))
print('este valor esta escrito em minúsculo?', '{}', a.islower(), '{}'.format('\033[36m', '\033[m'))
print('este valor é identificavel?', '{}', a.isidentifier(), '{}'.format('\033[36m', '\033[m'))
print('este valor é númerico?', '{}', a.isnumeric(), '{}'.format('\033[36m', '\033[m'))
print('este valor é imprimível?', '{}', a.isprintable(), '{}'.format('\033[36m', '\033[m'))
print('este valor é um espaço?', '{}', a.isspace(), '{}'.format('\033[36m', '\033[m'))
print('este valor é tem toda palavra iniciada por uma letra maiúscula?', '{}', a.istitle(), '{}'.format('\033[36m', '\033[m'))
print('este valor está escrito em maiúsculo?', '{}', a.isupper(), '{}'.format('\033[36m', '\033[m'))
